-- AlterTable
ALTER TABLE "SalaryProfile" ADD COLUMN     "deductEIS" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "deductEPF" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "deductSOCSO" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "hoursPerDay" DOUBLE PRECISION NOT NULL DEFAULT 7.5,
ADD COLUMN     "salaryBasis" TEXT NOT NULL DEFAULT 'monthly';
